=== Queliath/XML-XSD-DOM-Parser-Task/xml/menu.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://training.by/XML_XDS_DOM_Parser"
        xmlns:tns="http://training.by/XML_XDS_DOM_Parser">

    <element name="menu">
        <complexType>
            <sequence>
                <element name="kind" type="tns:Kind" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    
    <complexType name="Kind">
        <sequence>
            <element name="kind-name" type="string"/>
            <element name="kind-content" type="tns:KindContent"/>
        </sequence>
    </complexType>

    <complexType name="KindContent">
        <sequence>
            <element name="dish" type="tns:Dish" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Dish">
        <sequence>
            <element name="dish-photo" type="string"/>
            <element name="dish-name" type="string"/>
            <element name="dish-description" type="string"/>
            <element name="dish-portion" type="string"/>
            <element name="dish-price" type="string"/>
        </sequence>
    </complexType>

</schema>

=== Queliath/XML-XSD-DOM-Parser-Task/xml/menu.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<m:menu xmlns:m="http://training.by/XML_XDS_DOM_Parser"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://training.by/XML_XDS_DOM_Parser menu.xsd">
    <kind>
        <kind-name>Холодные закуски</kind-name>
        <kind-content>
            <dish>
                <dish-photo>madeDish.jgp</dish-photo>
                <dish-name>Ассорти рыбное</dish-name>
                <dish-description>Слабосоленая форель, семга</dish-description>
                <dish-portion>100/20/15</dish-portion>
                <dish-price>800</dish-price>
            </dish>
            <dish>
                <dish-photo>basturma.jpg</dish-photo>
                <dish-name>Бастурма</dish-name>
                <dish-description>Вяленая вырезка из говяжьего мяса</dish-description>
                <dish-portion>50/5</dish-portion>
                <dish-price>600</dish-price>
            </dish>
            <dish>
                <dish-photo>seniorTomato.jgp</dish-photo>
                <dish-name>Сеньор Помидор</dish-name>
                <dish-description>Помидор, фаршированный сырным муссом</dish-description>
                <dish-portion>150/1</dish-portion>
                <dish-price>150</dish-price>
            </dish>
        </kind-content>
    </kind>
    <kind>
        <kind-name>Горячие закуски</kind-name>
        <kind-content>
            <dish>
                <dish-photo>julien.jgp</dish-photo>
                <dish-name>Жульен</dish-name>
                <dish-description>с курицей</dish-description>
                <dish-portion>120/1</dish-portion>
                <dish-price>145</dish-price>
            </dish>
            <dish>
                <dish-photo>escargo.jgp</dish-photo>
                <dish-name>Эскарго</dish-name>
                <dish-description>Виноградные улитки, фаршированные по бургундски</dish-description>
                <dish-portion>12 шт.</dish-portion>
                <dish-price>230</dish-price>
            </dish>
        </kind-content>
    </kind>
</m:menu>
